id: I200692F2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:32:10+00:00'
last_modified: '2022-06-08T14:28:33.496530+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11808
  title: སྐྱེས་བུ་གསུམ་གྱི་ཉམས་སུ་བླང་བའི་བྱང་ཆུབ་ལམ་གྱི་རིམ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    222F:
      image_group_id: I1KG11816
      title: ''
      total_pages: 402
      order: 1
      base_file: 222F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
