id: P010557
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:53.294349
source_metadata:
  id: bdr:W1KG11808
  title: སྐྱེས་བུ་གསུམ་གྱི་ཉམས་སུ་བླང་བའི་བྱང་ཆུབ་ལམ་གྱི་རིམ་པ།
  author: ''
  volumes:
    0022b49cbb2547e398c7f2dfc3cc0022:
      image_group_id: I1KG11816
      title: ''
      volume_number: 1
      total_pages: 402
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
